name: Occupy the Vote
favicon: null
layout_spectrum: 0.43555719405412674
typography_spectrum: 0.1271431902423501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.38607061211951077
  lightness: 0.7440574883949012
  saturation: 0.31098780245520175
  rhythmicContrast: 0.06810789345763624
purpose: []
